# Generated by Django 6.0.2 on 2026-03-03 03:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Современная среда для ускоренного развития детей по научно-исследовательским и инженерно-техническим направлениям', max_length=400, verbose_name='Подзаголовок hero-блока'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='РРЦ «Кванториум» Сахалин', max_length=200, verbose_name='Заголовок hero-блока'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Вступительный текст'),
        ),
    ]
