# Generated by Django 6.0.2 on 2026-03-06 00:30

from django.db import migrations, models


def update_hero_title(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    HomePage.objects.filter(hero_title='РРЦ «Кванториум» Сахалин').update(hero_title='РРЦ «Кванториум»')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='РРЦ «Кванториум»', max_length=200, verbose_name='Заголовок hero-блока'),
        ),
        migrations.RunPython(update_hero_title, noop),
    ]
