# Generated by Django 6.0.2 on 2026-03-03 03:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'О нас',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EmployeesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
            ],
            options={
                'verbose_name': 'Страница сотрудников',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.CharField(choices=[('management', 'Руководство'), ('aero', 'АЭРО'), ('it', 'АЙТИ'), ('robo', 'ПРОМРОБО'), ('hitech', 'ХАЙТЕК'), ('vrar', 'VR/AR'), ('energy', 'ЭНЕРДЖИ'), ('design', 'ПРОМДИЗАЙН'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Отдел/Квантум')),
                ('bio', wagtail.fields.RichTextField(blank=True, verbose_name='О сотруднике')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
