# Generated by Django 6.0.2 on 2026-03-03 05:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial_employees'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Сотрудник (устаревшее)', 'verbose_name_plural': 'Сотрудники (устаревшее)'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('management', 'Руководство'), ('aero', 'АЭРО'), ('it', 'АЙТИ'), ('robo', 'ПРОМРОБО'), ('hitech', 'ХАЙТЕК'), ('vrar', 'VR/AR'), ('energy', 'ЭНЕРДЖИ'), ('design', 'ПРОМДИЗАЙН'), ('media', 'Медиа'), ('mobile', 'Мобильный комплекс'), ('methodist', 'Методист'), ('organizer', 'Педагог-организатор'), ('engineer', 'Инженер'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Отдел/Квантум'),
        ),
        migrations.CreateModel(
            name='EmployeePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('role', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.CharField(choices=[('management', 'Руководство'), ('aero', 'АЭРО'), ('it', 'АЙТИ'), ('robo', 'ПРОМРОБО'), ('hitech', 'ХАЙТЕК'), ('vrar', 'VR/AR'), ('energy', 'ЭНЕРДЖИ'), ('design', 'ПРОМДИЗАЙН'), ('media', 'Медиа'), ('mobile', 'Мобильный комплекс'), ('methodist', 'Методист'), ('organizer', 'Педагог-организатор'), ('engineer', 'Инженер'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Отдел/Квантум')),
                ('bio', wagtail.fields.RichTextField(blank=True, verbose_name='О сотруднике')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('wagtailcore.page',),
        ),
    ]
