# Generated by Django 6.0.2 on 2026-03-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_employee_options_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepage',
            name='direction',
            field=models.CharField(blank=True, help_text='Например: 3D-моделирование, VR/AR, АЭРО/ГЕО. Отображается под должностью.', max_length=150, verbose_name='Направление (для мобильного комплекса)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('management', 'Руководство'), ('aero', 'АЭРО'), ('it', 'АЙТИ'), ('robo', 'ПРОМРОБО'), ('hitech', 'ХАЙТЕК'), ('vrar', 'VR/AR'), ('energy', 'ЭНЕРДЖИ'), ('design', 'ПРОМДИЗАЙН'), ('media', 'Медиа'), ('mobile', 'Мобильный комплекс'), ('methodist', 'Методисты'), ('specialist', 'Специалисты'), ('organizer', 'Педагоги-организаторы'), ('engineer', 'Инженеры'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Отдел/Квантум'),
        ),
        migrations.AlterField(
            model_name='employeepage',
            name='department',
            field=models.CharField(choices=[('management', 'Руководство'), ('aero', 'АЭРО'), ('it', 'АЙТИ'), ('robo', 'ПРОМРОБО'), ('hitech', 'ХАЙТЕК'), ('vrar', 'VR/AR'), ('energy', 'ЭНЕРДЖИ'), ('design', 'ПРОМДИЗАЙН'), ('media', 'Медиа'), ('mobile', 'Мобильный комплекс'), ('methodist', 'Методисты'), ('specialist', 'Специалисты'), ('organizer', 'Педагоги-организаторы'), ('engineer', 'Инженеры'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Отдел/Квантум'),
        ),
    ]
