# Generated by Django 6.0.2 on 2026-03-05 05:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_mobile_directions_and_specialist'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Таблица расписания (HTML)')),
            ],
            options={
                'verbose_name': 'Расписание занятий',
                'verbose_name_plural': 'Расписание занятий',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'О нас (текстовая страница)', 'verbose_name_plural': 'О нас (текстовые страницы)'},
        ),
    ]
