# Generated by Django 6.0.2 on 2026-03-05 05:20

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_add_schedule_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepage',
            name='schedule_table_html',
            field=models.TextField(blank=True, help_text='Вставка готовой HTML-таблицы. Если задано — выводится вместо поля выше.', verbose_name='Таблица расписания (HTML)'),
        ),
        migrations.AlterField(
            model_name='schedulepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Таблица расписания (редактор)'),
        ),
    ]
