# Generated by Django 6.0.2 on 2026-03-03 03:40

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вступление')),
            ],
            options={
                'verbose_name': 'Раздел «Квантумы»',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QuantumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание (для карточки)')),
                ('age_range', models.CharField(default='7–17 лет', max_length=20, verbose_name='Возрастной диапазон')),
                ('max_students', models.PositiveIntegerField(default=12, verbose_name='Макс. учеников в группе')),
                ('accent_color', models.CharField(choices=[('#6366f1', 'Индиго'), ('#0ea5e9', 'Голубой'), ('#f59e0b', 'Янтарный'), ('#10b981', 'Зелёный'), ('#8b5cf6', 'Фиолетовый'), ('#f97316', 'Оранжевый'), ('#ec4899', 'Розовый')], default='#6366f1', max_length=7, verbose_name='Цвет акцента')),
                ('icon_emoji', models.CharField(default='🔬', help_text='Emoji для карточки квантума', max_length=4, verbose_name='Иконка (emoji)')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Описание программы')),
            ],
            options={
                'verbose_name': 'Квантум',
                'verbose_name_plural': 'Квантумы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QuantumTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(default='Старший педагог доп. образования', max_length=200, verbose_name='Должность')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='quantums.quantumpage')),
            ],
            options={
                'verbose_name': 'Педагог',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
